#%RAML 0.8

title: Video Service
version: v1
baseUri: http://video-service.prod.bxm.net.au/
mediaType: application/json
/video/mrss:
  displayName: Get all videos
  get:
      description: |
        Retrieves latest videos from brightcove cms api

/video/playlists/{playlist_id}/mrss:
  displayName: Get video feeds by playlist id
  Get:
      description: |
        Retrieves latest videos from brightcove cms api by playlist id, it is equivilent to retrieving videos by alias of this playlist id.
        example:
        /video/playlists/4631348873001/mrss

/video/playlists/{playlist_alias}/mrss:
  displayName: Get video feeds by playlist alias 
  Get:
      description: |
        Retrieves latest videos from brightcove cms api by playlist alias, it is equivilent to retrieving videos by playlist id of this alias.
        example:
        /video/playlists/elle/mrss

/video/folders/{folder_id}/mrss:
  displayName: Get video feeds by folder id
  Get:
      description: |
        Retrieves latest videos from brightcove cms api by playlist id, it is equivilent to retrieving videos by alias of this folder id.
        example:
        /video/folders/597979723bfb3d7fa191c87a/mrss

/video/folders/{folder_alias}/mrss:
  displayName: Get video feeds by folder alias 
  Get:
      description: |
        Retrieves latest videos from brightcove cms api by playlist alias, it is equivilent to retrieving videos by folder id of this alias.
        example:
        /video/folders/food/mrss





