#%RAML 0.8

title: Video Service
version: v1
baseUri: http://video-service.prod.bxm.net.au/
mediaType: application/json
/video/mrss:
  displayName: Get all latest videos feeds over the last 7 days from all brands with max 20 videos each brand
  get:
      description: |
        Retrieves latest JW Player videos from all brands with max 20 videos each brand

/video/playlist/{playlist_id}/mrss:
  displayName: Get video feeds by playlist id
  Get:
      description: |
        Retrieves all JW Player videos by playlist id.
        example:
        /video/playlist/ca4ZfbXt/mrss

/video/playlist/{brand_name}/mrss:
  displayName: Get video feeds by brand name
  Get:
      description: |
        Retrieves all JW Player videos by brand name.
        example:
        /video/playlist/MSN-NTL/mrss





