# This dockerfile is designed to be run inside the new ECS infrastructure
FROM 317367993082.dkr.ecr.ap-southeast-2.amazonaws.com/node-base-lite-aws:latest
MAINTAINER Richard Lennox <rlennox@bauerxcelmedia.com.au>

RUN mkdir /app
ADD ./src /app

WORKDIR /app

EXPOSE 3000

CMD ["npm", "start"]